"""empty message

Revision ID: 55ccd1aaddaf
Revises: beaf7fe6a34d
Create Date: 2025-01-14 15:49:49.010828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ccd1aaddaf'
down_revision: Union[str, None] = 'beaf7fe6a34d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
