"""empty message

Revision ID: 3c04efd64c44
Revises: 154dee322e1e
Create Date: 2025-01-20 21:07:11.521078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c04efd64c44'
down_revision: Union[str, None] = '154dee322e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=26),
               type_=sa.String(length=78),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(length=78),
               type_=sa.VARCHAR(length=26),
               existing_nullable=False)
    # ### end Alembic commands ###
