"""empty message

Revision ID: fb84f25a14f3
Revises: 55ccd1aaddaf
Create Date: 2025-01-15 20:19:32.363305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb84f25a14f3'
down_revision: Union[str, None] = '55ccd1aaddaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('game_name', sa.String(length=50), nullable=False),
    sa.Column('tag_line', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('puuid', sa.String(length=50), nullable=False),
    sa.Column('map_name', sa.String(length=50), nullable=False),
    sa.Column('game_mode', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('headshot_percentage', sa.Float(), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_comments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_comments')
    op.drop_table('matches')
    op.drop_table('users')
    # ### end Alembic commands ###
